### PR TITLE
LRQA-61832

### PR DESCRIPTION
**Pull request by dereckalexander**

### CODE REVIEW

**Comment by dereckalexander** [comment]
ci:test:sf

**Review by palomaanunes — APPROVED** [review]
Approved.

**Review by palomaanunes — APPROVED** [review]
The format requested by Brian recently also is applied correctly, such as: [4adaddb](https://github.com/brianchandotcom/liferay-portal/commit/4adaddb26cda50ba7c0e206492398ca69f9e7318) [c47781c](https://github.com/brianchandotcom/liferay-portal/commit/c47781c8bc5523cbe5b1f5faec473d2724f8d751) [00227a3](https://github.com/brianchandotcom/liferay-portal/commit/00227a3d152c7d4740a7574ddb4aa3dd87586c99) [b6c2144](https://github.com/brianchandotcom/liferay-portal/commit/b6c2144c8aedd7fd24a17bbd41d68f3a62b3307e)

**Comment by dereckalexander** [comment]
ci:test:forward

**Comment by dereckalexander** [comment]
ci:forward

**Pull request closed without merging**
