### PR TITLE
LRQA-60924

### PR DESCRIPTION
**Pull request by dereckalexander**
Changing IMAGE_FIELD_SELECT selector.

### CODE REVIEW

**Comment by dereckalexander** [comment]
ci:test:sf

**Comment by dereckalexander** [comment]
ci:test:relevant

**Comment by dereckalexander** [comment]
ci:test:acceptance

**Comment by dereckalexander** [comment]
ci:test:stable

**Comment by dereckalexander** [comment]
ci:help

**Comment by dereckalexander** [comment]
ci:test:data-engine

**Review by palomaanunes — APPROVED** [review]
Changes are approved

**Comment by palomaanunes** [comment]
@dereckalexander the failures raised in your PR are not related to your changes, so you are able to forward this PR to brian!

The source format to be done manually, required by brian in the last guilherme's PR was proper applied here too: [4adaddb](https://github.com/brianchandotcom/liferay-portal/commit/4adaddb26cda50ba7c0e206492398ca69f9e7318) [c47781c](https://github.com/brianchandotcom/liferay-portal/commit/c47781c8bc5523cbe5b1f5faec473d2724f8d751) [00227a3](https://github.com/brianchandotcom/liferay-portal/commit/00227a3d152c7d4740a7574ddb4aa3dd87586c99) [b6c2144](https://github.com/brianchandotcom/liferay-portal/commit/b6c2144c8aedd7fd24a17bbd41d68f3a62b3307e).

**Comment by dereckalexander** [comment]
ci:forward

**Pull request closed without merging**
