### PR TITLE
LRQA-66430 LocalizableSetToFalseAndTrueFieldGroup test

### PR DESCRIPTION
**Pull request by dereckalexander**
[LRQA-66430](https://issues.liferay.com/browse/LRQA-66430) Automate Test Scenario 28.09 of Data Engine Test Map

### CODE REVIEW

**Comment by dereckalexander** [comment]
ci:test:sf

**Comment by dereckalexander** [comment]
ci:test:sf

**Review by emanuelfisilva — APPROVED** [review]
LGTM

**Comment by emanuelfisilva** [comment]
Great work. Thanks @dereckalexander 
Forwarded https://github.com/emanuelfisilva/liferay-portal/pull/152

**Pull request closed without merging**
